Add configuration for an external authenticated mail relay (like Gmail)

diff --git a/overlay/etc/sv/postfix/run b/overlay/etc/sv/postfix/run
--- a/overlay/etc/sv/postfix/run
+++ b/overlay/etc/sv/postfix/run
@@ -1,8 +1,33 @@
 #!/bin/bash
 
-
+# Get a valid SSL certificate for postfix
+if [ ! -f /etc/postfix/cacert.pem ]; then
+    echo "cacert.pem not found; downloading thawte pem file..."
+    cd /etc/ssl/certs/
+    wget https://www.thawte.com/roots/thawte_Premium_Server_CA.pem
+    mv thawte_Premium_Server_CA.pem Thawte_Premium_Server_CA.pem
+    cat Thawte_Premium_Server_CA.pem | tee -a /etc/postfix/cacert.pem
+fi
+if [ ! -z "${MAIL_MYNETWORKS}" ]; then
+    echo "setting mynetworks = ${MAIL_MYNETWORKS}"
+    postconf -e mynetworks="${MAIL_MYNETWORKS}"
+fi
 if ! [ "${MAIL_RELAY_HOST}" = "" ]; then
-    sed -i "s/relayhost =.*/relayhost = ${MAIL_RELAY_HOST}/" /etc/postfix/main.cf
+    postconf relayhost=${MAIL_RELAY_HOST}
+fi
+if ! [ "${MAIL_RELAY_HOST}" = "" ] && [ -z "${MAIL_RELAY_USERNAME}" ] && [ -z "${MAIL_RELAY_PASSWORD}" ]; then
+    echo "${MAIL_RELAY_HOST}    ${MAIL_RELAY_USERNAME}:${MAIL_RELAY_PASSWORD}" > /etc/postfix/sasl_passwd
+    postmap /etc/postfix/sasl_passwd
+    postconf relayhost=${MAIL_RELAY_HOST}
+    postconf compatibility_level=2
+    postconf smtp_sasl_auth_enable=yes
+    postconf smtp_sasl_password_maps=hash:/etc/postfix/sasl_passwd
+    postconf smtp_sasl_security_options=noanonymous
+    postconf smtp_tls_CAfile=/etc/postfix/cacert.pem
+    postconf smtp_use_tls=yes
+    rm /etc/postfix/sasl_passwd
+    unset POSTFIX_EMAIL
+    unset POSTFIX_EMAILPASS
 fi
 if ! [ "${MAIL_INET_PROTOCOLS}" = "" ]; then 
     sed -i "s/inet_protocols =.*/inet_protocols = ${MAIL_INET_PROTOCOLS}/" /etc/postfix/main.cf
